---
extends: default
rules:
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  indentation:
    spaces: 2
    indent-sequences: whatever
    check-multi-line-strings: false
  line-length:
    max: 120
    ignore: |
      charts/saleor-core/values.yaml
  document-start: disable
  new-line-at-end-of-file: enable

ignore: |
  node_modules/
  saleor_core
  saleor_core_dev
  saleor_dashboard
  saleor_storefront
  **/templates/**/*.yaml
  **/templates/*.yaml
