# @format
---
stages:
  - stage: helm_push
    displayName: Push saleor helm charts
    # condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    condition: always()
    dependsOn: []
    jobs:
      - deployment: helm_push_approval
        displayName: Approval for push to registry
        dependsOn: []
        continueOnError: false
        timeoutInMinutes: 1296000
        cancelTimeoutInMinutes: 1296000
        environment: "Push saleor helm charts"
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "approval required"

      - job: push_saleor_helm_charts
        displayName: Push saleor helm charts to github pages
        dependsOn: [helm_push_approval]
        condition: succeeded()
        steps:
          - template: ../init_step.yaml

          - task: Bash@3
            displayName: Push saleor helm charts
            inputs:
              targetType: "inline"
              workingDirectory: "$(Build.Repository.LocalPath)"
              failOnStderr: false
              noProfile: true
              noRc: true
              script: |
                make push_updated_charts
            env:
              CR_TOKEN: $(crToken)

