apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi
