apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuredisk-pgdata-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
