# @format

# TODO

postgresql:
  enabled: true
  persistence:
    existingClaim: pgdata-pvc
  existingSecret: saleor-custom
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 11.9.0-debian-10-r73
    pullPolicy: IfNotPresent
    debug: true
  postgresqlUsername: postgres
  postgresqlDatabase: saleordb
  resources:
    requests:
      cpu: 125m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  psp:
    create: false
  rbac:
    create: false
  replication:
    enabled: false

redis:
  enabled: true
  persistence:
    existingClaim: redis-pvc

nfs-server-provisioner:
  enabled: true

saleor-core:
  enabled: true
  persistence:
    existingClaim: core-pvc

saleor-storefront:
  enabled: true

saleor-dashboard:
  enabled: true
